version: "3.8"
services:
  # EL CEREBRO (Base de datos y API)
  apexo-backend:
    image: muchobien/pocketbase:latest
    restart: always
    volumes:
      - apexo_data:/pb_data

  # LA CARA (La interfaz moderna que quieres)
  apexo-frontend:
    build:
      context: https://github.com/Dariocoding/apexo # Cambia por TU fork
      dockerfile: Dockerfile
    restart: always
    environment:
      - VITE_API_URL=https://dentalapi.zenmail.to # El dominio del backend
    depends_on:
      - apexo-backend
    # Aquí pondrás el dominio principal, ej: app.tuconsultorio.com

volumes:
  apexo_data:
